package com.wxy.work.entity;
// Generated 2017-3-22 22:28:25 by Hibernate Tools 4.3.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Hall generated by hbm2java
 */
@Entity
@Table(name = "hall", catalog = "work")
public class Hall implements java.io.Serializable {

	private HallId id;
	private Cinema cinema;
	private Integer allCount;
	private Integer leftSeatCount;

	public Hall() {
	}

	public Hall(HallId id, Cinema cinema) {
		this.id = id;
		this.cinema = cinema;
	}

	public Hall(HallId id, Cinema cinema, Integer allCount, Integer leftSeatCount) {
		this.id = id;
		this.cinema = cinema;
		this.allCount = allCount;
		this.leftSeatCount = leftSeatCount;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "number", column = @Column(name = "number", nullable = false)),
			@AttributeOverride(name = "cinemaId", column = @Column(name = "cinema_id", nullable = false)) })
	public HallId getId() {
		return this.id;
	}

	public void setId(HallId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_id", nullable = false, insertable = false, updatable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@Column(name = "all_count")
	public Integer getAllCount() {
		return this.allCount;
	}

	public void setAllCount(Integer allCount) {
		this.allCount = allCount;
	}

	@Column(name = "left_seat_count")
	public Integer getLeftSeatCount() {
		return this.leftSeatCount;
	}

	public void setLeftSeatCount(Integer leftSeatCount) {
		this.leftSeatCount = leftSeatCount;
	}

}
