package com.wxy.work.entity;
// Generated 2017-3-22 22:28:25 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HallId generated by hbm2java
 */
@Embeddable
public class HallId implements java.io.Serializable {

	private int number;
	private int cinemaId;

	public HallId() {
	}

	public HallId(int number, int cinemaId) {
		this.number = number;
		this.cinemaId = cinemaId;
	}

	@Column(name = "number", nullable = false)
	public int getNumber() {
		return this.number;
	}

	public void setNumber(int number) {
		this.number = number;
	}

	@Column(name = "cinema_id", nullable = false)
	public int getCinemaId() {
		return this.cinemaId;
	}

	public void setCinemaId(int cinemaId) {
		this.cinemaId = cinemaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HallId))
			return false;
		HallId castOther = (HallId) other;

		return (this.getNumber() == castOther.getNumber()) && (this.getCinemaId() == castOther.getCinemaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumber();
		result = 37 * result + this.getCinemaId();
		return result;
	}

}
