package com.wxy.work.entity;
// Generated 2017-3-27 10:02:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Invite generated by hbm2java
 */
@Entity
@Table(name = "invite", catalog = "work")
public class Invite implements java.io.Serializable {

	private int inviteId;
	private Movie movie;
	private User userByResponseUserId;
	private User userByRequestUserId;
	private String inviteTopic;
	private String requestContent;
	private String responseContent;
	private String status;
	private Date inviteTime;
	private String inviteArea;
	private String inviteSex;

	public Invite() {
	}

	public Invite(int inviteId, Movie movie, User userByRequestUserId, String inviteTopic) {
		this.inviteId = inviteId;
		this.movie = movie;
		this.userByRequestUserId = userByRequestUserId;
		this.inviteTopic = inviteTopic;
	}

	public Invite(int inviteId, Movie movie, User userByResponseUserId, User userByRequestUserId, String inviteTopic,
			String requestContent, String responseContent, String status, Date inviteTime, String inviteArea,
			String inviteSex) {
		this.inviteId = inviteId;
		this.movie = movie;
		this.userByResponseUserId = userByResponseUserId;
		this.userByRequestUserId = userByRequestUserId;
		this.inviteTopic = inviteTopic;
		this.requestContent = requestContent;
		this.responseContent = responseContent;
		this.status = status;
		this.inviteTime = inviteTime;
		this.inviteArea = inviteArea;
		this.inviteSex = inviteSex;
	}

	@Id

	@Column(name = "invite_id", unique = true, nullable = false)
	public int getInviteId() {
		return this.inviteId;
	}

	public void setInviteId(int inviteId) {
		this.inviteId = inviteId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "invite_movie_id", nullable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "response_user_id")
	public User getUserByResponseUserId() {
		return this.userByResponseUserId;
	}

	public void setUserByResponseUserId(User userByResponseUserId) {
		this.userByResponseUserId = userByResponseUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "request_user_id", nullable = false)
	public User getUserByRequestUserId() {
		return this.userByRequestUserId;
	}

	public void setUserByRequestUserId(User userByRequestUserId) {
		this.userByRequestUserId = userByRequestUserId;
	}

	@Column(name = "invite_topic", nullable = false)
	public String getInviteTopic() {
		return this.inviteTopic;
	}

	public void setInviteTopic(String inviteTopic) {
		this.inviteTopic = inviteTopic;
	}

	@Column(name = "request_content")
	public String getRequestContent() {
		return this.requestContent;
	}

	public void setRequestContent(String requestContent) {
		this.requestContent = requestContent;
	}

	@Column(name = "response_content")
	public String getResponseContent() {
		return this.responseContent;
	}

	public void setResponseContent(String responseContent) {
		this.responseContent = responseContent;
	}

	@Column(name = "status")
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "invite_time", length = 19)
	public Date getInviteTime() {
		return this.inviteTime;
	}

	public void setInviteTime(Date inviteTime) {
		this.inviteTime = inviteTime;
	}

	@Column(name = "invite_area")
	public String getInviteArea() {
		return this.inviteArea;
	}

	public void setInviteArea(String inviteArea) {
		this.inviteArea = inviteArea;
	}

	@Column(name = "invite_sex")
	public String getInviteSex() {
		return this.inviteSex;
	}

	public void setInviteSex(String inviteSex) {
		this.inviteSex = inviteSex;
	}

}
