package com.wxy.work.entity;
// Generated 2017-3-27 10:02:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie", catalog = "work")
public class Movie implements java.io.Serializable {

	private Integer movieId;
	private String movieName;
	private String type;
	private String description;
	private Integer timeRange;
	private String language;
	private String directors;
	private String actors;
	private String picturePath;
	private String grade;
	private Integer status;
	private Date showTime;
	private float price;
	private Set<Screen> screens = new HashSet<Screen>(0);
	private Set<Invite> invites = new HashSet<Invite>(0);
	private Set<MovieComment> movieComments = new HashSet<MovieComment>(0);

	public Movie() {
	}

	public Movie(String movieName, String type, float price) {
		this.movieName = movieName;
		this.type = type;
		this.price = price;
	}

	public Movie(String movieName, String type, String description, Integer timeRange, String language,
			String directors, String actors, String picturePath, String grade, Integer status, Date showTime,
			float price, Set<Screen> screens, Set<Invite> invites, Set<MovieComment> movieComments) {
		this.movieName = movieName;
		this.type = type;
		this.description = description;
		this.timeRange = timeRange;
		this.language = language;
		this.directors = directors;
		this.actors = actors;
		this.picturePath = picturePath;
		this.grade = grade;
		this.status = status;
		this.showTime = showTime;
		this.price = price;
		this.screens = screens;
		this.invites = invites;
		this.movieComments = movieComments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "movie_id", unique = true, nullable = false)
	public Integer getMovieId() {
		return this.movieId;
	}

	public void setMovieId(Integer movieId) {
		this.movieId = movieId;
	}

	@Column(name = "movie_name", nullable = false)
	public String getMovieName() {
		return this.movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "time_range")
	public Integer getTimeRange() {
		return this.timeRange;
	}

	public void setTimeRange(Integer timeRange) {
		this.timeRange = timeRange;
	}

	@Column(name = "language")
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "directors")
	public String getDirectors() {
		return this.directors;
	}

	public void setDirectors(String directors) {
		this.directors = directors;
	}

	@Column(name = "actors")
	public String getActors() {
		return this.actors;
	}

	public void setActors(String actors) {
		this.actors = actors;
	}

	@Column(name = "picture_path")
	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	@Column(name = "grade")
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "show_time", length = 19)
	public Date getShowTime() {
		return this.showTime;
	}

	public void setShowTime(Date showTime) {
		this.showTime = showTime;
	}

	@Column(name = "price", nullable = false, precision = 12, scale = 0)
	public float getPrice() {
		return this.price;
	}

	public void setPrice(float price) {
		this.price = price;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<Screen> getScreens() {
		return this.screens;
	}

	public void setScreens(Set<Screen> screens) {
		this.screens = screens;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<Invite> getInvites() {
		return this.invites;
	}

	public void setInvites(Set<Invite> invites) {
		this.invites = invites;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<MovieComment> getMovieComments() {
		return this.movieComments;
	}

	public void setMovieComments(Set<MovieComment> movieComments) {
		this.movieComments = movieComments;
	}

}
