package com.wxy.work.entity;
// Generated 2017-3-27 10:02:09 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MovieComment generated by hbm2java
 */
@Entity
@Table(name = "movie_comment", catalog = "work")
public class MovieComment implements java.io.Serializable {

	private Integer commentId;
	private Movie movie;
	private User user;
	private String commentContent;
	private Date commentTime;

	public MovieComment() {
	}

	public MovieComment(Movie movie, User user, String commentContent) {
		this.movie = movie;
		this.user = user;
		this.commentContent = commentContent;
	}

	public MovieComment(Movie movie, User user, String commentContent, Date commentTime) {
		this.movie = movie;
		this.user = user;
		this.commentContent = commentContent;
		this.commentTime = commentTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "comment_id", unique = true, nullable = false)
	public Integer getCommentId() {
		return this.commentId;
	}

	public void setCommentId(Integer commentId) {
		this.commentId = commentId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_id", nullable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "comment_content", nullable = false)
	public String getCommentContent() {
		return this.commentContent;
	}

	public void setCommentContent(String commentContent) {
		this.commentContent = commentContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "comment_time", length = 19)
	public Date getCommentTime() {
		return this.commentTime;
	}

	public void setCommentTime(Date commentTime) {
		this.commentTime = commentTime;
	}

}
