package com.wxy.work.entity;
// Generated 2017-2-24 19:51:24 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movie", catalog = "work")
public class Movie implements java.io.Serializable {

	private String movieName;
	private String type;
	private String description;
	private Integer timeRange;
	private String language;
	private String directors;
	private String actors;
	private String picturePath;
	private String grade;
	private Set<ScreenSchedule> screenSchedules = new HashSet<ScreenSchedule>(0);

	public Movie() {
	}

	public Movie(String movieName, String type) {
		this.movieName = movieName;
		this.type = type;
	}

	public Movie(String movieName, String type, String description, Integer timeRange, String language,
			String directors, String actors, String picturePath, String grade, Set<ScreenSchedule> screenSchedules) {
		this.movieName = movieName;
		this.type = type;
		this.description = description;
		this.timeRange = timeRange;
		this.language = language;
		this.directors = directors;
		this.actors = actors;
		this.picturePath = picturePath;
		this.grade = grade;
		this.screenSchedules = screenSchedules;
	}

	@Id

	@Column(name = "movie_name", unique = true, nullable = false)
	public String getMovieName() {
		return this.movieName;
	}

	public void setMovieName(String movieName) {
		this.movieName = movieName;
	}

	@Column(name = "type", nullable = false)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "time_range")
	public Integer getTimeRange() {
		return this.timeRange;
	}

	public void setTimeRange(Integer timeRange) {
		this.timeRange = timeRange;
	}

	@Column(name = "language")
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@Column(name = "directors")
	public String getDirectors() {
		return this.directors;
	}

	public void setDirectors(String directors) {
		this.directors = directors;
	}

	@Column(name = "actors")
	public String getActors() {
		return this.actors;
	}

	public void setActors(String actors) {
		this.actors = actors;
	}

	@Column(name = "picture_path")
	public String getPicturePath() {
		return this.picturePath;
	}

	public void setPicturePath(String picturePath) {
		this.picturePath = picturePath;
	}

	@Column(name = "grade")
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
	public Set<ScreenSchedule> getScreenSchedules() {
		return this.screenSchedules;
	}

	public void setScreenSchedules(Set<ScreenSchedule> screenSchedules) {
		this.screenSchedules = screenSchedules;
	}

}
