package com.wxy.work.entity;
// Generated 2017-3-27 0:09:43 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "work")
public class Order implements java.io.Serializable {

	private Integer orderId;
	private Screen screen;
	private Seat seat;
	private User user;
	private Float allPrice;
	private String status;
	private Date buyTime;
	private String telephone;

	public Order() {
	}

	public Order(User user, String status) {
		this.user = user;
		this.status = status;
	}

	public Order(Screen screen, Seat seat, User user, Float allPrice, String status, Date buyTime, String telephone) {
		this.screen = screen;
		this.seat = seat;
		this.user = user;
		this.allPrice = allPrice;
		this.status = status;
		this.buyTime = buyTime;
		this.telephone = telephone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "screen_id")
	public Screen getScreen() {
		return this.screen;
	}

	public void setScreen(Screen screen) {
		this.screen = screen;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "seat_id")
	public Seat getSeat() {
		return this.seat;
	}

	public void setSeat(Seat seat) {
		this.seat = seat;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "all_price", precision = 12, scale = 0)
	public Float getAllPrice() {
		return this.allPrice;
	}

	public void setAllPrice(Float allPrice) {
		this.allPrice = allPrice;
	}

	@Column(name = "status", nullable = false)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "buy_time", length = 19)
	public Date getBuyTime() {
		return this.buyTime;
	}

	public void setBuyTime(Date buyTime) {
		this.buyTime = buyTime;
	}

	@Column(name = "telephone")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
