package com.wxy.work.entity;
// Generated 2017-3-22 22:28:25 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ScreenSchedule generated by hbm2java
 */
@Entity
@Table(name = "screen_schedule", catalog = "work")
public class ScreenSchedule implements java.io.Serializable {

	private Integer id;
	private Cinema cinema;
	private Movie movie;
	private int hall;
	private Date openTime;
	private Float price;

	public ScreenSchedule() {
	}

	public ScreenSchedule(Cinema cinema, Movie movie, int hall, Date openTime) {
		this.cinema = cinema;
		this.movie = movie;
		this.hall = hall;
		this.openTime = openTime;
	}

	public ScreenSchedule(Cinema cinema, Movie movie, int hall, Date openTime, Float price) {
		this.cinema = cinema;
		this.movie = movie;
		this.hall = hall;
		this.openTime = openTime;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cinema_id", nullable = false)
	public Cinema getCinema() {
		return this.cinema;
	}

	public void setCinema(Cinema cinema) {
		this.cinema = cinema;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "movie_name", nullable = false)
	public Movie getMovie() {
		return this.movie;
	}

	public void setMovie(Movie movie) {
		this.movie = movie;
	}

	@Column(name = "hall", nullable = false)
	public int getHall() {
		return this.hall;
	}

	public void setHall(int hall) {
		this.hall = hall;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "open_time", nullable = false, length = 19)
	public Date getOpenTime() {
		return this.openTime;
	}

	public void setOpenTime(Date openTime) {
		this.openTime = openTime;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

}
