package com.wxy.work.entity;
// Generated 2017-3-27 0:14:30 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SeatPlan generated by hbm2java
 */
@Entity
@Table(name = "seat_plan", catalog = "work")
public class SeatPlan implements java.io.Serializable {

	private int seatPlanId;
	private Hall hall;
	private Integer perRow;
	private Integer perCol;
	private Integer rows;
	private Integer cols;

	public SeatPlan() {
	}

	public SeatPlan(int seatPlanId) {
		this.seatPlanId = seatPlanId;
	}

	public SeatPlan(int seatPlanId, Hall hall, Integer perRow, Integer perCol, Integer rows, Integer cols) {
		this.seatPlanId = seatPlanId;
		this.hall = hall;
		this.perRow = perRow;
		this.perCol = perCol;
		this.rows = rows;
		this.cols = cols;
	}

	@Id

	@Column(name = "seat_plan_id", unique = true, nullable = false)
	public int getSeatPlanId() {
		return this.seatPlanId;
	}

	public void setSeatPlanId(int seatPlanId) {
		this.seatPlanId = seatPlanId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hall_id")
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@Column(name = "per_row")
	public Integer getPerRow() {
		return this.perRow;
	}

	public void setPerRow(Integer perRow) {
		this.perRow = perRow;
	}

	@Column(name = "per_col")
	public Integer getPerCol() {
		return this.perCol;
	}

	public void setPerCol(Integer perCol) {
		this.perCol = perCol;
	}

	@Column(name = "rows")
	public Integer getRows() {
		return this.rows;
	}

	public void setRows(Integer rows) {
		this.rows = rows;
	}

	@Column(name = "cols")
	public Integer getCols() {
		return this.cols;
	}

	public void setCols(Integer cols) {
		this.cols = cols;
	}

}
