package com.wxy.work.entity;
// Generated 2017-3-27 10:02:09 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Seat generated by hbm2java
 */
@Entity
@Table(name = "seat", catalog = "work")
public class Seat implements java.io.Serializable {

	private Integer seatId;
	private Hall hall;
	private Integer seatRow;
	private Integer seatCol;
	private int seatNum;
	private int seatState;
	private Set<Order> orders = new HashSet<Order>(0);

	public Seat() {
	}

	public Seat(Hall hall, int seatNum, int seatState) {
		this.hall = hall;
		this.seatNum = seatNum;
		this.seatState = seatState;
	}

	public Seat(Hall hall, Integer seatRow, Integer seatCol, int seatNum, int seatState, Set<Order> orders) {
		this.hall = hall;
		this.seatRow = seatRow;
		this.seatCol = seatCol;
		this.seatNum = seatNum;
		this.seatState = seatState;
		this.orders = orders;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "seat_id", unique = true, nullable = false)
	public Integer getSeatId() {
		return this.seatId;
	}

	public void setSeatId(Integer seatId) {
		this.seatId = seatId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "hall_id", nullable = false)
	public Hall getHall() {
		return this.hall;
	}

	public void setHall(Hall hall) {
		this.hall = hall;
	}

	@Column(name = "seat_row")
	public Integer getSeatRow() {
		return this.seatRow;
	}

	public void setSeatRow(Integer seatRow) {
		this.seatRow = seatRow;
	}

	@Column(name = "seat_col")
	public Integer getSeatCol() {
		return this.seatCol;
	}

	public void setSeatCol(Integer seatCol) {
		this.seatCol = seatCol;
	}

	@Column(name = "seat_num", nullable = false)
	public int getSeatNum() {
		return this.seatNum;
	}

	public void setSeatNum(int seatNum) {
		this.seatNum = seatNum;
	}

	@Column(name = "seat_state", nullable = false)
	public int getSeatState() {
		return this.seatState;
	}

	public void setSeatState(int seatState) {
		this.seatState = seatState;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seat")
	public Set<Order> getOrders() {
		return this.orders;
	}

	public void setOrders(Set<Order> orders) {
		this.orders = orders;
	}

}
