package com.wxy.work.entity;
// Generated 2017-3-22 22:28:25 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name = "ticket", catalog = "work")
public class Ticket implements java.io.Serializable {

	private Integer id;
	private Order order;
	private String movie;
	private String cinema;
	private Integer hall;
	private Integer seat;
	private Float price;
	private String telephone;

	public Ticket() {
	}

	public Ticket(Order order, String movie, String cinema, Integer hall, Integer seat, Float price, String telephone) {
		this.order = order;
		this.movie = movie;
		this.cinema = cinema;
		this.hall = hall;
		this.seat = seat;
		this.price = price;
		this.telephone = telephone;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id")
	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	@Column(name = "movie")
	public String getMovie() {
		return this.movie;
	}

	public void setMovie(String movie) {
		this.movie = movie;
	}

	@Column(name = "cinema")
	public String getCinema() {
		return this.cinema;
	}

	public void setCinema(String cinema) {
		this.cinema = cinema;
	}

	@Column(name = "hall")
	public Integer getHall() {
		return this.hall;
	}

	public void setHall(Integer hall) {
		this.hall = hall;
	}

	@Column(name = "seat")
	public Integer getSeat() {
		return this.seat;
	}

	public void setSeat(Integer seat) {
		this.seat = seat;
	}

	@Column(name = "price", precision = 12, scale = 0)
	public Float getPrice() {
		return this.price;
	}

	public void setPrice(Float price) {
		this.price = price;
	}

	@Column(name = "telephone")
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
