package com.wxy.work.entity;
// Generated 2017-3-23 11:33:14 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "work")
public class User implements java.io.Serializable {

	private Integer userId;
	private String userEmail;
	private String userPassword;
	private String userUsername;
	private String userNickname;
	private String userSex;
	private String userPhone;
	private String userPhoto;
	private Date userBirthday;
	private String userBornCity;
	private String userLivingCity;

	public User() {
	}

	public User(String userEmail, String userPassword) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
	}

	public User(String userEmail, String userPassword, String userUsername, String userNickname, String userSex,
			String userPhone, String userPhoto, Date userBirthday, String userBornCity, String userLivingCity) {
		this.userEmail = userEmail;
		this.userPassword = userPassword;
		this.userUsername = userUsername;
		this.userNickname = userNickname;
		this.userSex = userSex;
		this.userPhone = userPhone;
		this.userPhoto = userPhoto;
		this.userBirthday = userBirthday;
		this.userBornCity = userBornCity;
		this.userLivingCity = userLivingCity;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "user_email", nullable = false)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "user_password", nullable = false)
	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	@Column(name = "user_username")
	public String getUserUsername() {
		return this.userUsername;
	}

	public void setUserUsername(String userUsername) {
		this.userUsername = userUsername;
	}

	@Column(name = "user_nickname")
	public String getUserNickname() {
		return this.userNickname;
	}

	public void setUserNickname(String userNickname) {
		this.userNickname = userNickname;
	}

	@Column(name = "user_sex")
	public String getUserSex() {
		return this.userSex;
	}

	public void setUserSex(String userSex) {
		this.userSex = userSex;
	}

	@Column(name = "user_phone")
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "user_photo")
	public String getUserPhoto() {
		return this.userPhoto;
	}

	public void setUserPhoto(String userPhoto) {
		this.userPhoto = userPhoto;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "user_birthday", length = 19)
	public Date getUserBirthday() {
		return this.userBirthday;
	}

	public void setUserBirthday(Date userBirthday) {
		this.userBirthday = userBirthday;
	}

	@Column(name = "user_born_city")
	public String getUserBornCity() {
		return this.userBornCity;
	}

	public void setUserBornCity(String userBornCity) {
		this.userBornCity = userBornCity;
	}

	@Column(name = "user_living_city")
	public String getUserLivingCity() {
		return this.userLivingCity;
	}

	public void setUserLivingCity(String userLivingCity) {
		this.userLivingCity = userLivingCity;
	}

}
